const GAME_BOARD_WIDTH = 8,
	GAME_BOARD_HEIGHT = 16,
	animation = [
		{x: [3, 3], y: [10, 11], rotation: ["left", "right"], hand: "up"},
		{x: [3, 2], y: [10, 10], rotation: ["down", "up"], hand: "up"},
		{x: [2, 2], y: [10, 9], rotation: ["right", "left"], hand: "up"},
		{x: [1, 2], y: [9, 9], rotation: ["up", "down"], hand: "up"},
		{x: [1, 1], y: [8, 9], rotation: ["left", "right"], hand: "middle"},
		{x: [1, 0], y: [8, 8], rotation: ["down", "up"], hand: "middle"},
		{x: [1, 1], y: [8, 7], rotation: ["right", "left"], hand: "middle"},
		{x: [0, 1], y: [7, 7], rotation: ["up", "down"], hand: "down"},
		{x: [1, 1], y: [6, 7], rotation: ["left", "right"], hand: "down"},
		{x: [1, 0], y: [6, 6], rotation: ["down", "up"], hand: "down"},
		{x: [1, 1], y: [6, 5], rotation: ["right", "left"], hand: "down"},
		{x: [0, 1], y: [5, 5], rotation: ["up", "down"], hand: "down"},
		{x: [1, 1], y: [4, 5], rotation: ["left", "right"], hand: "down"},
		{x: [1, 0], y: [4, 4], rotation: ["down", "up"], hand: "down"},
		{x: [1, 1], y: [4, 3], rotation: ["right", "left"], hand: "down"},
		{x: [0, 1], y: [3, 3], rotation: ["up", "down"], hand: "down"},
		{x: [1, 1], y: [2, 3], rotation: ["left", "right"], hand: "down"},
		{x: [1, 0], y: [2, 2], rotation: ["down", "up"], hand: "down"},
		{x: [2, 2], y: [2, 1], rotation: ["right", "left"], hand: "down"},
		{x: [1, 2], y: [1, 1], rotation: ["up", "down"], hand: "down"},
		{x: [2, 2], y: [0, 1], rotation: ["left", "right"], hand: "down"},
		{x: [3, 3], y: [0, 1], rotation: ["left", "right"], hand: "down"},
		{x: [4, 4], y: [0, 1], rotation: ["left", "right"], hand: "down"},
		{x: [5, 5], y: [0, 1], rotation: ["left", "right"], hand: "down"}
	],
	covidsPositions = [
		{top: 14, left: 7},
		{top: 14, left: 6},
		{top: 14, left: 5},
		{top: 14, left: 4},
		{top: 15, left: 3},
		{top: 16, left: 2},
		{top: 16, left: 2},
		{top: 17, left: 2},
		{top: 18, left: 3},
		{top: 19, left: 3},
		{top: 19, left: 4},
		{top: 19, left: 5},
		{top: 19, left: 6},
		{top: 19, left: 7},
		{top: 18, left: 8},
		{top: 17, left: 8},
		{top: 16, left: 8},
		{top: 15, left: 8}
	];